name: shri_amareshwar_mahadev
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.5.0
  dio: ^5.4.0
  shared_preferences: ^2.2.0
  device_info_plus: ^11.3.3
  geolocator: ^13.0.3
  get: ^4.6.5
  image_picker: ^1.0.7
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.2.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/